### ISSUE TITLE
Cannot run eval.py because there is no Module ylib.

### ISSUE THREAD

**Issue by L-avenir** [USRC-SEA/OmniMotionGPT#1]
I can't run eval.py. Because it gives the following error

Traceback (most recent call last):
  File "/home/vrlab/Documents/OmniMotionGPT/OmGPT/motion_mapping/evl/eval.py", line 31, in <module>
    from motion_datasets import get_dataloader  # =================================
  File "/home/vrlab/Documents/OmniMotionGPT/OmGPT/motion_mapping/evl/motion_datasets/__init__.py", line 33, in <module>
    from ylib.deforming_things_4d.prior import smal_animal_names_v1_train  # ======
ModuleNotFoundError: No module named 'ylib‘

**Comment by dolphin9** [comment]
I also met this problem, I searched ylib in google but the results are not I need

**Comment by dolphin9** [comment]
I find the lib ： [ylib](https://github.com/zshyang/ylib)

**Comment by lucciffer** [comment]
> I find the lib ： [ylib](https://github.com/zshyang/ylib)

i downloaded and installed the ylib from the link you commented. But now, its asking for checkpoints. and im not able to find them anywhere. any help here? 
thanks.
